[tool.pylint.main]
ignore-patterns = ["venv", ".venv"]
jobs = 0
persistent = true

[tool.pylint.messages_control]
disable = [
    "missing-module-docstring",
    "missing-class-docstring",
    "missing-function-docstring",
    "too-few-public-methods",
    "broad-except",
    "import-outside-toplevel",
    "trailing-whitespace",
    "logging-fstring-interpolation",
    "unused-import",
    "no-name-in-module",
    "protected-access",
    "multiple-statements",
    "unspecified-encoding",
]

[tool.pylint.format]
max-line-length = 120

[tool.mypy]
python_version = "3.10"
ignore_missing_imports = true